version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      
      - pip3 install -r tests/requirements.txt
      - pip3 install pytest
      - pip3 install pytest-cov
     
      - mkdir test-reports
  build:
    commands:
      - python pytest -v tests/ --junitxml=tests/junit.xml  --cov=com --cov-report=tests/cov.xml 



reports:
  pytest_reports:
    files:
      - junit.xml
    base-directory: tests
    file-format: JUNITXML 
      
   
       
